### ISSUE TITLE
Switch ec2 task to key:value format

### ISSUE THREAD

**Issue by gavD** [radify/radiian#74]
The playbook generates stuff like:

```yaml
  - name: Launch Instance
    ec2:
      image: 'ami-47a23a30'
      instance_type="{{ instance_type }}"
      keypair='hello-world'
      instance_tags='{"Environment":"hw","Class":"hw-immutable","Name":"hw (immutable)"}'
      region='{{ region }}'
      aws_zone='{{ region }}{{ aws_zone }}'
      group_id='< redacted >'
      wait=true
    register: ec2_info
```

This format is nicer:

```yaml
  - name: Launch Instance
    ec2:
      image: 'ami-fce3c696'
      instance_type: "{{ instance_type }}"
      keypair: 'hello-world'
      instance_tags:
        Environment:"hw"
        Name: "hw (immutable)"
      region: '{{ region }}'
      aws_zone: '{{ region }}{{ aws_zone }}'
      group_id: '< redacted >'
      vpc_subnet_id: '< redacted >'
      wait: true
      assign_public_ip: true
    register: ec2_info
```
